### ISSUE TITLE
BUG - Plugin 0.2.1 not published in DBT Hub repo

### ISSUE THREAD

**Issue by pawelngei** [fivetran/dbt_klaviyo#10]
I realized that after merging https://github.com/fivetran/dbt_klaviyo/pull/8 (release https://github.com/fivetran/dbt_klaviyo/releases/tag/v0.2.1 ) you didn't push it to https://hub.getdbt.com/fivetran/klaviyo/latest/ , which causes our current build (with dbt-utils/star updated) to crash.

I see it's on https://github.com/dbt-labs/hubcap , so I don't know what might be the reason for it not being published.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @pawelngei looks like `0.2.1` is live on the hub! Also our team will be starting a new sprint on Wednesday of this week and will be reviewing your PR!

**Comment by pawelngei** [comment]
Thanks a lot @fivetran-joemarkiewicz ! If there are any problems, please let me know what would be the best way to write tests to cover them :)
