### ISSUE TITLE
BUG - incorporate `source_relation` into the `unique_key` for incremental models

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_klaviyo#13]
**Are you a current Fivetran customer?** 

fivetran made issue

**Describe the bug**

i haven't come across an error yet, but i just realized we missed a spot where we need to add `source_relation`. so in the incremental model configs, we provide `event_id` as the unique key, but we should really be making a surrogate key hashed on event id and the source relation for proper merging and such. 

https://github.com/fivetran/dbt_klaviyo/blob/main/models/intermediate/int_klaviyo__event_attribution.sql#L4

and 

https://github.com/fivetran/dbt_klaviyo/blob/main/models/klaviyo__events.sql#L4

**Please indicate the level of urgency** 

not super urgent i suppose, but it would be a very quick fix

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
This fix has been merged into the latest release of the package!
