### ISSUE TITLE
[Feature] API Updates

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_klaviyo#28]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Connector was updated to a new version of the Klaviyo API. [Here](https://fivetran.com/docs/applications/klaviyo/changelog) is the list of updates. We will need to update this and the source package for compatibility with the updates.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-reneeli** [comment]
This has been addressed in the latest release and as such will be closing this out!
