### ISSUE TITLE
[Bug] dbt run failure due to deprecated INTEGRATION table

### ISSUE THREAD

**Issue by robertspragg** [fivetran/dbt_klaviyo#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

- Our dbt cloud Daily Runner began failing after we did a full re-sync of our historical Klaviyo data.
- The old Klaviyo data contained an `INTEGRATION` table, but this was replaced with the `METRIC` table according to the [September 2023 release notes](https://fivetran.com/docs/applications/klaviyo/changelog#september2023)
- Our existing klaviyo transformations rely upon the `INTEGRATION` table for making our various analytics marts

### Relevant error log or model output

```shell
From dbt cloud
`ERROR creating view model analytics_stg_klaviyo.stg_klaviyo__integration_tmp [ERROR in 3.09s]`

`15:49:38  Completed with 1 error and 0 warnings:
15:49:38  Database Error in model stg_klaviyo__integration_tmp (models/tmp/stg_klaviyo__integration_tmp.sql)
15:49:38    SQL compilation error:
15:49:38    Object 'RAW.KLAVIYO.INTEGRATION' does not exist or not authorized.
15:49:38    compiled SQL at target/run/klaviyo_source/models/tmp/stg_klaviyo__integration_tmp.sql`
```

### Expected behavior

When integration table was deprecated, the underlying queries should have been updated to point to the `METRIC` table

### dbt Project configurations

version: "1.0.0"
vars:
  klaviyo_database: RAW
  klaviyo_schema: KLAVIYO

### Package versions

packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.4
  - package: fivetran/klaviyo
    version: 0.4.1
  - package: fivetran/klaviyo_source
    version: 0.4.1

### What database are you using dbt with?

snowflake

### dbt Version

1.0.9

### Additional Context

Fivetran Support Engineer suggested I make this PR

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-reneeli** [comment]
Hi @robertspragg! We've been made aware of the connector updates and are working this week to push out a new release for this package, which will address this!

**Comment by robertspragg** [comment]
Thank you for the update!

**Comment by fivetran-reneeli** [comment]
Hi @robertspragg , this has been addressed in the latest release of the package. As such we'll be closing this out! Let us know if there's anything else.

**Comment by robertspragg** [comment]
Thank you so much!
