### ISSUE TITLE
[Bug] klaviyo__campaigns table contains null values for SMS campaigns

### ISSUE THREAD

**Issue by vandanaveeraraghavan** [fivetran/dbt_klaviyo#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The klaviyo__campaigns table contains lots of different metrics for each campaign, however all metrics related to SMS campaigns are null. 

We know that these metrics are specifically related to SMS because they have `_sms` as part of their name. We also checked that the data for email campaigns looked OK and those were fine. The issue is only related to SMS campaigns. 
 
It appears that what might have happened is that the transformations logic did not update automatically to pull in these SMS campaign metrics when the upgrade to Klaviyo API v3 happened. 

### Relevant error log or model output

```shell
Quickstart Klaviyo transform model
```

### Expected behavior

The klaviyo__campaigns table should contain non-null values for SMS campaigns.

### dbt Project configurations

Don't have a dbt project as this is an issue with Quickstart Klaviyo model

### Package versions

version: 0.7.1 (should be the latest version as this is the same package that the Quickstart model uses as well)

### What database are you using dbt with?

bigquery

### dbt Version

N/A - This is an issue with Quickstart Klaviyo model

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by vandanaveeraraghavan** [comment]
Raised this issue on behalf of customer Rad Global.

Group ID - `madame_capsize`

cc @fivetran-seanodriscoll

**Comment by fivetran-reneeli** [comment]
Hi @vandanaveeraraghavan , when you say the metrics are missing for SMS campaigns, are you talking about the following?
![image](https://github.com/fivetran/dbt_klaviyo/assets/91097070/5b114e5d-09ea-4f2c-992c-6881a3d06211) Or can you give the specific fields that are showing up as null unexpectedly.

We have a variable allowing customers to configure which metrics get passed through (see below, and expand the dropdown). I am curious whether these columns exist but values are null, or you're seeing that the columns don't exist at all-- in which case they would have to be configured in the customers project yml, except this customer is using Quickstart so it wouldn't be feasbile.

https://github.com/fivetran/dbt_klaviyo/blob/main/README.md#filtering-conversion-metrics-to-pivot-out

**Comment by fivetran-joemarkiewicz** [comment]
After investigating this we found that the core reason for the discrepancy was due to a limitation from the connector. I will close this out as there is no action from the dbt package side.
