### ISSUE TITLE
[Feature] Tags for package models

### ISSUE THREAD

**Issue by irmacorado** [fivetran/dbt_klaviyo#39]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Run all the models of this package with `dbt build -s tag:+fivetran_dbt_klavyio`.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-jamie** [comment]
hey there! Question for ya first: do you see an advantage to using tags to run package models as opposed to doing `dbt build -s +klaviyo` ?

**Comment by irmacorado** [comment]
didn't realize that was an option. that works perfectly, thank you!
