### ISSUE TITLE
BUG - rollback snowflake fix for dbt_utils.star

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_klaviyo#7]
**Are you a current Fivetran customer?** 

Fivetran created PR

**Describe the bug**

With the patch release of [dbt-utils v0.7.3](https://github.com/dbt-labs/dbt-utils/releases/tag/0.7.3) the snowflake uppercase fix no longer is needed / may cause ambiguous column errors in the following models
- klaviyo__events
- klaviyo__campaigns
- klaviyo__flows
- klaviyo__persons

**Additional context**
 
Can adapt the fix from jira https://github.com/fivetran/dbt_jira/pull/40

**Comment by fivetran-reneeli** [comment]
PR has been merged and release has been integrated; deleting this issue
