### ISSUE TITLE
BUG - attribution issue?

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_klaviyo#9]
**Are you a current Fivetran customer?** 

this is from a custmoer

**Describe the bug**

no attribution is occurring in the package even if the following events are provided as event_types 
`['Ordered Product', 'Checkout Started', 'Viewed Product', 'Active on Site', 'Placed Order', 'Received Email', 'Opened Email', 'Clicked Email’]`

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as it seems this was a config issue and has been resolved.
